<?php

namespace Tests\Unit;

use Faker\Factory;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ABM_ComercializadorTest extends TestCase
{
    use DatabaseMigrations;

    public $factory;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function data()
    {
        $f = Factory::create('App\Capitulo');
        return [
            'nombre' => $f->firstName(),
            'dni' => $f->randomNumber(8),
            'cuit' => $f->randomNumber(8),
            'telefono' => $f->randomNumber(8),
            'usuario' => 'prueba',
            'apellido' => $f->lastName,
            'domicilio' =>  $f->address,
            'email' => $f->email,
            'porcentaje_colocacion' => $f->randomNumber(2),
            'password' => 'prueba'
        ];

    }
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testAltaComercializador()
    {
        $data = $this->data();
        $col = collect();
        $col->put('usuario', $data['usuario']);
        $col->put('email', $data['email']);
        $response = $this->post('abm_comercializador', $data);
        $data['usuario'] = 1;
        unset($data['password']);
        $this->assertDatabaseHas('comercializadores', $data);
        $this->assertDatabaseHas('users', $col->toArray());
    }

    public function testUpdateComercializador()
    {

        $data = $this->data();
        $data2 = $this->data();
        $response = $this->post('abm_comercializador', $data);
        $col = collect();
        $col->put('usuario', $data2['usuario']);
        $col->put('email', $data2['email']);
        $data2['id'] = 1;

        $response = $this->put('abm_comercializador/1', $data2);
        $data2['usuario'] = 1;
        unset($data2['password']);
        $this->assertDatabaseHas('comercializadores', $data2);
        $this->assertDatabaseHas('users', $col->toArray());
    }
}
