<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class CorrerVtoTest extends TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testCorrerVto()
    {
        $data = collect(['cuotable_id' => 1, 'cuotable_type' => 'App\Ventas', 'importe' => 200, '']);
        $ventasRepo = new VentasRepo();
        $elem = $request->all();
        $id = 1;
        $dias = 5
        $venta = $ventasRepo->findWithCuotas($id);
        $venta->correrVto($dias);
    }
}
